const languages = [
    {
        id: 'python',
        name: 'Python',
        year: 1991,
        creator: 'Guido van Rossum',
        useCase: 'Data Science, Web, AI',
        description: 'Designed for readability and minimalist elegance.',
        tags: ['Dynamic', 'Easy', 'Popular'],
        category: 'AI',
        color: '#3776ab',
        example: `# Python Essence: List Comprehension\nsquares = [x**2 for x in range(10) if x % 2 == 0]`,
        executionSteps: ['Source (.py)', 'Bytecode (.pyc)', 'Python VM', 'Output'],
        history: [{ year: 1989, event: 'Started' }, { year: 1991, event: 'Released' }],
        mascot: 'assets/python_mascot.png',
        mascotQuote: 'Indent your code, not your life!',
        funEpisode: "Named after Monty Python, not the snake!"
    },
    {
        id: 'javascript',
        name: 'JavaScript',
        year: 1995,
        creator: 'Brendan Eich',
        useCase: 'Web, Mobile, Server',
        description: 'The ubiquitous language of the web.',
        tags: ['Async', 'Web', 'Fast'],
        category: 'Web',
        color: '#f7df1e',
        example: `// JS Essence: Async/Await\nconst data = await fetch('/api').then(r => r.json());`,
        executionSteps: ['Source', 'Parser', 'JIT Compiler (V8)', 'Machine Code'],
        history: [{ year: 1995, event: 'Created in 10 days' }],
        mascot: 'assets/js_mascot.png',
        mascotQuote: 'I run the world in every browser!',
        funEpisode: "Created in just 10 days for Netscape."
    },
    {
        id: 'html',
        name: 'HTML',
        year: 1993,
        creator: 'Tim Berners-Lee',
        useCase: 'Web Structure',
        description: 'The fundamental markup for all web documents.',
        tags: ['Markup', 'Web', 'Base'],
        category: 'Web',
        color: '#e34f26',
        example: `<!-- HTML Essence: Semantics -->\n<article>\n  <h1>Structure is King</h1>\n</article>`,
        executionSteps: ['Markup', 'DOM Tree', 'Render Tree', 'Screen'],
        history: [{ year: 1991, event: 'First site' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'I am the structure.',
        funEpisode: "The first web page is still live at info.cern.ch!"
    },
    {
        id: 'css',
        name: 'CSS',
        year: 1996,
        creator: 'Håkon Wium Lie',
        useCase: 'Web Styling',
        description: 'The design language that brings the web to life.',
        tags: ['Style', 'Web', 'Visual'],
        category: 'Web',
        color: '#1572b6',
        example: `/* CSS Essence: Cascade & Layout */\n.grid { display: grid; gap: 1rem; }`,
        executionSteps: ['Styles', 'CSSOM', 'Layout Engine', 'Paint'],
        history: [{ year: 1994, event: 'Proposed' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'I make things beautiful.',
        funEpisode: "Before CSS, browsers used <font> and <center> tags for styling."
    },
    {
        id: 'c_lang',
        name: 'C',
        year: 1972,
        creator: 'Dennis Ritchie',
        useCase: 'OS, Kernels, Embedded',
        description: 'Absolute control over the machine. The basis of modern computing.',
        tags: ['Foundation', 'Fast', 'Power'],
        category: 'Systems',
        color: '#a8b9cc',
        example: `/* C Essence: Pointers */\nint *p = malloc(sizeof(int));\n*p = 42;`,
        executionSteps: ['Source', 'Compiler (GCC)', 'Object Code', 'Native Binary'],
        history: [{ year: 1972, event: 'Born at Bell Labs' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'Direct and powerful.',
        funEpisode: "Unix was rewritten in C specifically for portability."
    },
    {
        id: 'rust',
        name: 'Rust',
        year: 2010,
        creator: 'Graydon Hoare',
        useCase: 'Systems, WASM',
        description: 'Blazing fast speed with memory safety guaranteed.',
        tags: ['Safe', 'Systems', 'Fast'],
        category: 'Systems',
        color: '#dea584',
        example: `// Rust Essence: Borrowing\nlet s2 = s1; // Move semantics`,
        executionSteps: ['Source', 'Borrow Checker', 'LLVM', 'Binary'],
        history: [{ year: 2010, event: 'Announced' }],
        mascot: 'assets/rust_mascot.png',
        mascotQuote: 'Fearless concurrency.',
        funEpisode: "Ferris the crab is the mascot!"
    },
    {
        id: 'cpp',
        name: 'C++',
        year: 1985,
        creator: 'Bjarne Stroustrup',
        useCase: 'Games, Systems',
        description: 'High-performance software and game engine giant.',
        tags: ['Fast', 'Low-level', 'OOP'],
        category: 'Systems',
        color: '#00599c',
        example: `// C++ Essence: Templates\ntemplate<typename T> T add(T a, T b);`,
        executionSteps: ['Source', 'Preprocessor', 'Compiler', 'Binary'],
        history: [{ year: 1979, event: 'Started' }],
        mascot: 'assets/cpp_mascot.png',
        mascotQuote: 'Zero-cost abstractions.',
        funEpisode: "Originally called 'C with Classes'."
    },
    {
        id: 'java',
        name: 'Java',
        year: 1995,
        creator: 'James Gosling',
        useCase: 'Enterprise, Android',
        description: 'The standard for large-scale, cross-platform software.',
        tags: ['Enterprise', 'OOP', 'Safe'],
        category: 'Enterprise',
        color: '#007396',
        example: `// Java Essence: Streams\nlist.stream().filter(n -> n > 0);`,
        executionSteps: ['Source', 'Bytecode', 'JVM', 'JIT Engine'],
        history: [{ year: 1995, event: 'Released' }],
        mascot: 'assets/java_mascot.png',
        mascotQuote: 'Write once, run anywhere.',
        funEpisode: "Java was originally called 'Oak'!"
    },
    {
        id: 'csharp',
        name: 'C#',
        year: 2000,
        creator: 'Anders Hejlsberg',
        useCase: 'Unity Games, Enterprise',
        description: 'Modern flagship for the .NET ecosystem.',
        tags: ['Unity', 'Enterprise', 'Modern'],
        category: 'Software',
        color: '#239120',
        example: `// C# Essence: LINQ\nvar top = users.Where(u => u.Active);`,
        executionSteps: ['Source', 'CIL (Bytecode)', 'CLR Runtime', 'Native Code'],
        history: [{ year: 2000, event: 'Released' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'The language of possibilities.',
        funEpisode: "Originally named 'Cool'."
    },
    {
        id: 'php',
        name: 'PHP',
        year: 1995,
        creator: 'Rasmus Lerdorf',
        useCase: 'Web Backend, CMS',
        description: 'The original script of the web, powering millions.',
        tags: ['Web', 'Scripting', 'Fast'],
        category: 'Backend',
        color: '#777bb4',
        example: `<?php // PHP Essence: Superglobals\necho $_GET['name'];`,
        executionSteps: ['Script', 'Zend Engine', 'Interpreter', 'Output'],
        history: [{ year: 1995, event: 'Born' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'I power the web.',
        funEpisode: "PHP stands for Hypertext Preprocessor."
    },
    {
        id: 'ruby',
        name: 'Ruby',
        year: 1995,
        creator: 'Yukihiro Matsumoto',
        useCase: 'Web (Rails)',
        description: 'Designed for programmer happiness and elegance.',
        tags: ['Elegant', 'Rails', 'Happiness'],
        category: 'Backend',
        color: '#cc342d',
        example: `# Ruby Essence: Blocks\n3.times { puts "Hello!" }`,
        executionSteps: ['Script', 'Parser', 'YARV VM', 'Result'],
        history: [{ year: 1995, event: 'Born' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'Human-centric code.',
        funEpisode: "Based on the concept of 'Least Astonishment'."
    },
    {
        id: 'swift',
        name: 'Swift',
        year: 2014,
        creator: 'Apple',
        useCase: 'iOS, macOS',
        description: 'Fast, safe replacement for Objective-C.',
        tags: ['Apple', 'Mobile', 'Fast'],
        category: 'Mobile',
        color: '#f05138',
        example: `// Swift Essence: Protocol Orient\nprotocol Greetable { func greet() }`,
        executionSteps: ['Source', 'SIL', 'LLVM', 'Binary'],
        history: [{ year: 2014, event: 'WWDC' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'Safety first.',
        funEpisode: "Swift's mascot represents a bird!"
    },
    {
        id: 'kotlin',
        name: 'Kotlin',
        year: 2011,
        creator: 'JetBrains',
        useCase: 'Android, Backend',
        description: 'Modern, safe alternative to Java on the JVM.',
        tags: ['Modern', 'Android', 'Safe'],
        category: 'Mobile',
        color: '#7f52ff',
        example: `// Kotlin Essence: Extensions\nfun String.shout() = this.toUpperCase()`,
        executionSteps: ['Source', 'Compiler', 'Bytecode', 'JVM'],
        history: [{ year: 2011, event: 'Released' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'Concise and safe.',
        funEpisode: "Named after an island near St. Petersburg."
    },
    {
        id: 'go',
        name: 'Go',
        year: 2009,
        creator: 'Google',
        useCase: 'Cloud, Systems',
        description: 'The standard for cloud-native infrastructure.',
        tags: ['Cloud', 'Concurrent', 'Simple'],
        category: 'Backend',
        color: '#00add8',
        example: `// Go Essence: Structs\ntype User struct { Name string }`,
        executionSteps: ['Source', 'Compiler', 'Static Binary', 'Run'],
        history: [{ year: 2009, event: 'Launched' }],
        mascot: 'assets/go_mascot.png',
        mascotQuote: 'Simple is better.',
        funEpisode: "The gopher mascot has no official name."
    },
    {
        id: 'sql',
        name: 'SQL',
        year: 1974,
        creator: 'IBM',
        useCase: 'Databases',
        description: 'Standard for relational measurement and query.',
        tags: ['Data', 'Declarative', 'Base'],
        category: 'Data',
        color: '#003b57',
        example: `-- SQL Essence: Joins\nSELECT * FROM a JOIN b ON a.id = b.id;`,
        executionSteps: ['Query', 'Optimizer', 'Plan', 'Data Fetch'],
        history: [{ year: 1974, event: 'Born' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'I find patterns.',
        funEpisode: "Originally called SEQUEL."
    },
    {
        id: 'r_lang',
        name: 'R',
        year: 1993,
        creator: 'Ihaka & Gentleman',
        useCase: 'Statistics, Data',
        description: 'The power of statistics in a script.',
        tags: ['Stats', 'Data', 'Visual'],
        category: 'Data',
        color: '#276bca',
        example: `# R Essence: Vectors\nx <- c(1, 10, 100); mean(x)`,
        executionSteps: ['Script', 'Parser', 'Interpreter (R)', 'Graphics Device'],
        history: [{ year: 1993, event: 'Born' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'Data is beautiful.',
        funEpisode: "Named after its creators Ross and Robert."
    },
    {
        id: 'dart',
        name: 'Dart',
        year: 2011,
        creator: 'Google',
        useCase: 'Mobile (Flutter)',
        description: 'Optimized for high-quality UI development.',
        tags: ['Flutter', 'Google', 'UI'],
        category: 'Mobile',
        color: '#0175c2',
        example: `// Dart Essence: Cascades\nvar p = Person()..name = "Bob"..save();`,
        executionSteps: ['Source', 'AOT/JIT Compiler', 'Flutter Engine', 'App'],
        history: [{ year: 2011, event: 'Launched' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'UI first.',
        funEpisode: "AOT compilation makes Flutter apps very fast!"
    },
    {
        id: 'lua',
        name: 'Lua',
        year: 1993,
        creator: 'Roberto Ierusalimschy',
        useCase: 'Game Scripts',
        description: 'Lightweight and embeddable scripting engine.',
        tags: ['Games', 'Fast', 'Small'],
        category: 'Scripting',
        color: '#000080',
        example: `-- Lua Essence: Tables\nlocal t = { x = 10, y = 20 }`,
        executionSteps: ['Script', 'Bytecode', 'Lua VM', 'Result'],
        history: [{ year: 1993, event: 'Born in Brazil' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'Small yet mighty.',
        funEpisode: "Lua means 'Moon' in Portuguese."
    },
    {
        id: 'haskell',
        name: 'Haskell',
        year: 1990,
        creator: 'Committee',
        useCase: 'Academia, Finance',
        description: 'Purely functional, lazy, and mathematically sound.',
        tags: ['Pure', 'Lazy', 'Math'],
        category: 'Functional',
        color: '#5e5086',
        example: `-- Haskell Essence: Currying\nadd x y = x + y`,
        executionSteps: ['Source', 'GHC Compiler', 'Lazy Eval', 'Binary'],
        history: [{ year: 1990, event: 'Born' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'Pure functions only.',
        funEpisode: "Named after logician Haskell Curry."
    },
    {
        id: 'lisp',
        name: 'Lisp',
        year: 1958,
        creator: 'John McCarthy',
        useCase: 'AI Research',
        description: 'Pioneer of functional logic and S-expressions.',
        tags: ['Functional', 'Ancient', 'AI'],
        category: 'Functional',
        color: '#3fb68b',
        example: `;; Lisp Essence: Recursion\n(defun fact (n) (if (= n 0) 1 (* n (fact (- n 1)))))`,
        executionSteps: ['Source', 'Parser', 'Eval', 'Result'],
        history: [{ year: 1958, event: 'Born' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'Code is data.',
        funEpisode: "Pioneered garbage collection and 'if' statements!"
    },
    {
        id: 'asm',
        name: 'Assembly',
        year: 1949,
        creator: 'Booth',
        useCase: 'Low-level tuning',
        description: 'Direct communication with CPU architecture.',
        tags: ['CPU', 'Fast', 'Hard'],
        category: 'Systems',
        color: '#6e4c13',
        example: `; ASM Essence: Syscall\nmov eax, 4 ; sys_write`,
        executionSteps: ['Mnemonics', 'Assembler', 'Linker', 'Machine Code'],
        history: [{ year: 1947, event: 'Born' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'I am the hardware.',
        funEpisode: "One line of C is many lines of ASM."
    },
    {
        id: 'bash',
        name: 'Bash',
        year: 1989,
        creator: 'Brian Fox',
        useCase: 'DevOps, CLI',
        description: 'The standard glue for Unix/Linux systems.',
        tags: ['CLI', 'Scripting', 'DevOps'],
        category: 'Scripting',
        color: '#4eaa25',
        example: `# Bash Essence: Pipe\ncat log | grep "ERROR"`,
        executionSteps: ['Commands', 'Parsing', 'Fork/Exec', 'I/O'],
        history: [{ year: 1989, event: 'Released' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'Automate everything.',
        funEpisode: "BASH = Bourne Again Shell."
    },
    {
        id: 'prolog',
        name: 'Prolog',
        year: 1972,
        creator: 'Colmerauer',
        useCase: 'Logic, AI',
        description: 'The definitive logic programming language.',
        tags: ['Logic', 'AI', 'Search'],
        category: 'Functional',
        color: '#74283c',
        example: `% Prolog Essence: Backtracking\nfather(X, Y) :- parent(X, Y), male(X).`,
        executionSteps: ['Facts', 'Rules', 'Inference', 'Solution'],
        history: [{ year: 1972, event: 'Born' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'Let logic decide.',
        funEpisode: "Prolog stands for 'Programmation en Logique'."
    },
    {
        id: 'per-l',
        name: 'Perl',
        year: 1987,
        creator: 'Larry Wall',
        useCase: 'CGI, Legacy',
        description: 'The Swiss Army Chainsaw of scripting.',
        tags: ['Scripting', 'Regex', 'Powerful'],
        category: 'Scripting',
        color: '#39457e',
        example: `# Perl Essence: Regex\n$text =~ s/old/new/g;`,
        executionSteps: ['Script', 'Compiler', 'Interpreter', 'Output'],
        history: [{ year: 1987, event: 'Born' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'More than one way.',
        funEpisode: "Known for its amazing text processing power."
    },
    {
        id: 'scala',
        name: 'Scala',
        year: 2004,
        creator: 'Martin Odersky',
        useCase: 'Big Data, JVM',
        description: 'Scalable language for functional enterprise.',
        tags: ['JVM', 'Typed', 'Functional'],
        category: 'Backend',
        color: '#dc322f',
        example: `// Scala Essence: Implicits\ncase class User(id: Int)`,
        executionSteps: ['Source', 'Compiler', 'Bytecode', 'JVM'],
        history: [{ year: 2004, event: 'Born' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'Scalability first.',
        funEpisode: "Portmanteau of Scalable and Language."
    },
    {
        id: 'elixir',
        name: 'Elixir',
        year: 2011,
        creator: 'José Valim',
        useCase: 'Real-time Apps',
        description: 'Concurrent and fault-tolerant on the Erlang VM.',
        tags: ['BEAM', 'Web', 'Concurrent'],
        category: 'Backend',
        color: '#4e2a8e',
        example: `# Elixir Essence: Pipe\n"hello" |> String.upcase()`,
        executionSteps: ['Source', 'Elixir Compiler', 'BEAM Bytecode', 'BEAM VM'],
        history: [{ year: 2011, event: 'Born' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'Fault tolerance.',
        funEpisode: "Discord handles 12M+ concurrent users with Elixir!"
    },
    {
        id: 'objc',
        name: 'Objective-C',
        year: 1984,
        creator: 'Brad Cox',
        useCase: 'Legacy iOS',
        description: 'The language that powered the first iPhone.',
        tags: ['Apple', 'OO', 'Legacy'],
        category: 'Software',
        color: '#438eff',
        example: `// ObjC Essence: Messaging\n[object performAction:param];`,
        executionSteps: ['Source', 'Compiler (LLVM)', 'Runtime Lib', 'Binary'],
        history: [{ year: 1984, event: 'Born' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'Dynamic messaging.',
        funEpisode: "Steve Jobs licensed it for NeXT computer."
    },
    {
        id: 'smalltalk',
        name: 'Smalltalk',
        year: 1972,
        creator: 'Alan Kay',
        useCase: 'OO Research',
        description: 'The purest approach to object-oriented programming.',
        tags: ['OO', 'Iconic', 'Pure'],
        category: 'Software',
        color: '#596706',
        example: `"Smalltalk Essence: Blocks"\n[ 1 + 2 ] value.`,
        executionSteps: ['Image', 'Object Space', 'Message JIT', 'Result'],
        history: [{ year: 1972, event: 'PARC' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'Everything is an object.',
        funEpisode: "Invented the concept of overlapping windows!"
    },
    {
        id: 'vhdl',
        name: 'VHDL',
        year: 1981,
        creator: 'US DOD',
        useCase: 'Chip Design',
        description: 'Hardware description for digital logic circuits.',
        tags: ['Hardware', 'FPGA', 'Logic'],
        category: 'Systems',
        color: '#adb2cb',
        example: `-- VHDL Essence: Signals\nsig <= a and b;`,
        executionSteps: ['Source', 'Synthesis', 'Layout', 'Hardware'],
        history: [{ year: 1981, event: 'DOD Project' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'Describing silicon.',
        funEpisode: "Used to simulate space shuttle electronics!"
    },
    {
        id: 'pascal',
        name: 'Pascal',
        year: 1970,
        creator: 'Niklaus Wirth',
        useCase: 'Education, GUI',
        description: 'Clean, structured, and strictly typed development.',
        tags: ['Clean', 'Safety', 'Formal'],
        category: 'Systems',
        color: '#27336e',
        example: `(* Pascal Essence: Units *)\nunit MyUtils; interface ...`,
        executionSteps: ['Source', 'Unit Parser', 'Compiler', 'Binary'],
        history: [{ year: 1970, event: 'Released' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'Structured beauty.',
        funEpisode: "Inspired Apple's early Mac OS code!"
    },
    {
        id: 'vb',
        name: 'Visual Basic',
        year: 1991,
        creator: 'Alan Cooper',
        useCase: 'Windows Apps',
        description: 'Revolutionized GUI development with drag-and-drop.',
        tags: ['Easy', 'GUI', 'Windows'],
        category: 'Software',
        color: '#1572b6',
        example: `' VB Essence: Form Logic\nForm_Load: Set Text = "Hi"`,
        executionSteps: ['Forms', 'Compiler', 'COM Runtime', 'Window'],
        history: [{ year: 1991, event: 'Born' }],
        mascot: 'assets/placeholder_mascot.png',
        mascotQuote: 'If-then-else GUI.',
        funEpisode: "The 'Father of VB' is also the father of UX personas."
    }
];
